cookie:
  expiry_days: 30
  key: some_key
  name: some_cookie_name
credentials:
  usernames:
    gataa:
      email: Agatha@gmail.com
      failed_login_attempts: 0
      first_name: Agatha
      last_name: Angelina
      level1: 0
      level1_passed: false
      level2: 0
      level2_passed: false
      level3: 0
      level3_passed: false
      logged_in: false
      password: $2b$12$.seqrSfWbEEuYuEx2uvbDe4L1pIsDvMKjkufPp/0L3rszVWlu7.IO
      password_hint: Agatha18*
      posttest: 0
      posttest_taken: false
      pretest: 0
      pretest_taken: false
      roles: null
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - agathaangel1826@gmail.com
